### ISSUE TITLE
Multiple implementations

### ISSUE THREAD

**Issue by leif81** [open-dis/open-dis-csharp#6]
From what I can tell there are multiple implementations of open dis C# in this repository. My head is spinning trying to figure out which one should be used.

e.g.

* [x] https://github.com/open-dis/open-dis-csharp/tree/master/C%23/DIS%231.0
* [ ] https://github.com/open-dis/open-dis-csharp/tree/master/C%23/DIS%232.0
* [x] https://github.com/open-dis/open-dis-csharp/tree/master/C%23Examples/DISnetSolution/DISnet
* [ ] https://github.com/open-dis/open-dis-csharp/tree/master/CSharpDis7
* [x] https://github.com/open-dis/open-dis-csharp/tree/master/Csharp

This is confusing as a maintainer and I'm guessing end users. Ideally we have at most two like the other language repositories; a dis6 and dis7 implementation.

**Comment by rodneyp290** [comment]
I had a look at the repo, and I've made a branch on a fork to start looking at this. The below is a summary of what I found:
- [C#/DIS#1.0Examples](https://github.com/open-dis/open-dis-csharp/tree/master/C%23/DIS%231.0/Examples/) is identical to [C#/Examples](https://github.com/open-dis/open-dis-csharp/tree/master/C%23/Examples/), except the later has binaries included
  - *Action Taken:* Remove C#Examples - commit [ae65eea](https://github.com/rodneyp290/open-dis-csharp/commit/ae65eea629069349ab29467cac6d266e498769f7)
- All *.cs files directly in [Csharp](https://github.com/open-dis/open-dis-csharp/tree/master/Csharp/) are empty - with the Subdirectories having the actual code in them.
  - *Action Taken:* Remove Csharp/*.cs - commit [7bc33a4](https://github.com/rodneyp290/open-dis-csharp/commit/7bc33a4fcc78cb5f8e2a14adb8531321b151bced)
- According to [C#/DIS#1.0/Readme.txt](https://github.com/open-dis/open-dis-csharp/blob/master/C%23/DIS%231.0/ReadMe.txt), C#/DIS#1.0 is code generated from open-dis_3.1.3.jar, presumably an old version open-dis-java.
  - *Action Taken:* Remove C#/DIS#1.0/ - commit [c6f32a1](https://github.com/rodneyp290/open-dis-csharp/commit/c6f32a18f1ce6d6ef9e0e08995357e2f5847a08b)

Beyond that, I'm not sure. My original instinct was to remove C# all together, but C#/DIS#2.0/ is the only directory that has been modified since the Initial Check-in commit, including:
- a commit regarding the correction of some bitwise operations
- and, the addition of some test apps

 C#/DIS#2.0/OpenDis does have a Dis1998 folder, so that is Version 6, yeah?

Oh, CSharpDis7 seems to be the only thing to reference dis7.

**DISCLAIMER:** My DIS knowledge is limited, I've been hunting through the issues for somethings I can do to learn more. Above decisions were made purely off diffing & grepping files, and the C#/DIS#1.0 ReadMe.txt file

**Comment by leif81** [comment]
@rodneyp290 thank you this is a fantastic analysis! I'll be looking at your PR in a moment.

**Comment by leif81** [comment]
I've also just now renamed the `C#/Dis#2.0` folder to `CSharpDis6` to be more clear now.

**Comment by leif81** [comment]
Now just to figure out what to do with the Csharp folder. I think it's another Dis6 implementation.

**Comment by leif81** [comment]
Ok `Csharp` folder was identical to `https://github.com/open-dis/open-dis-csharp/tree/master/CsharpDis6/OpenDis/Dis1998/Generated`. So I'm removing `Csharp`.

Thanks for your help getting the ball rolling @rodneyp290

**Comment by rodneyp290** [comment]
No Problem. Glad I could help out :+1:
